import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Terms of Service'), centerTitle: true),
      body: Markdown(data: _termsData, padding: const EdgeInsets.all(16)),
    );
  }

  static const String _termsData = '''
# Terms of Service

**Last Updated: December 05, 2025**

Welcome to **RapidVal**! By accessing or using our mobile application ("App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the App.

## 1. Acceptance of Terms

By creating an account or using RapidVal, you agree to comply with and be legally bound by these Terms and our Privacy Policy. These Terms apply to all visitors, users, and others who access or use the Service.

## 2. Description of Service

RapidVal is an AI-powered quiz and learning application designed to help users test their knowledge across various topics. The App generates quizzes, tracks progress, and provides performance analytics using Artificial Intelligence.

## 3. User Accounts

*   **Registration:** You may need to register for an account to access certain features. You agree to provide accurate, current, and complete information during the registration process.
*   **Security:** You are responsible for safeguarding the password that you use to access the App and for any activities or actions under your password.
*   **Eligibility:** You must be at least 13 years old to use the App.

## 4. User Content and Conduct

*   **AI Generation:** The quizzes and content generated by the App are created using Artificial Intelligence (Cerebras AI). While we strive for accuracy, we cannot guarantee that all information is 100% correct, complete, or up-to-date. You acknowledge that AI-generated content may occasionally contain errors or inaccuracies.
*   **Prohibited Use:** You agree not to use the App for any unlawful purpose or in any way that interrupts, damages, or impairs the service. You agree not to attempt to reverse engineer the App or its AI models.

## 5. Intellectual Property

The App and its original content (excluding content provided by users or generated by AI where applicable), features, and functionality are and will remain the exclusive property of RapidVal and its licensors. The App is protected by copyright, trademark, and other laws.

## 6. Termination

We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.

## 7. Limitation of Liability

In no event shall RapidVal, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
*   Your access to or use of or inability to access or use the App;
*   Any conduct or content of any third party on the App;
*   Any content obtained from the App; and
*   Unauthorized access, use or alteration of your transmissions or content.

## 8. Disclaimer

Your use of the App is at your sole risk. The App is provided on an "AS IS" and "AS AVAILABLE" basis. The App is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.

## 9. Changes to Terms

We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our App after those revisions become effective, you agree to be bound by the revised terms.

## 10. Contact Us

If you have any questions about these Terms, please contact us at:

**Email:** rapidval.ai@gmail.com
''';
}
