// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClF4p_OqG35ZaqWoTCByQRHSyXZZH323w',
    appId: '1:57305758196:web:da778f43dc329607fe61a1',
    messagingSenderId: '57305758196',
    projectId: 'rapidval',
    authDomain: 'rapidval.firebaseapp.com',
    storageBucket: 'rapidval.firebasestorage.app',
    measurementId: 'G-37XQQ8J6FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjMcy1cwr4PSppvnlhkO7y-2NkRcKglrM',
    appId: '1:57305758196:android:ec35feafcf04af54fe61a1',
    messagingSenderId: '57305758196',
    projectId: 'rapidval',
    storageBucket: 'rapidval.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClF4p_OqG35ZaqWoTCByQRHSyXZZH323w',
    appId: '1:57305758196:web:dfe32cba959e3a82fe61a1',
    messagingSenderId: '57305758196',
    projectId: 'rapidval',
    authDomain: 'rapidval.firebaseapp.com',
    storageBucket: 'rapidval.firebasestorage.app',
    measurementId: 'G-D3VW4SS3G7',
  );

}